<?php
/** @var $this \View\Template */
?>
<h1 class="header">Create Account</h1>

<form data-form="create-account-form" method="POST" class="container container_admin">
    <div class="container container_admin-input">
        <label for="first">First Name
            <input type="text" name="first">
        </label>
    </div>
    <div class="container container_admin-input">
        <label for="last">Last Name
            <input type="text" name="last">
        </label>
    </div>
    <div class="container container_admin-input">
        <label for="dob">Date of Birth
            <input type="text" name="dob">
        </label>
    </div>
    <div class="container container_admin-input">
        <label for="username">Username
            <input type="text" name="username">
        </label>
    </div>
    <div class="container container_admin-input">
        <label for="password">Password
            <input type="password" name="password">
        </label>
    </div>
    <div class="container">
        <input type="submit" value="Submit" class="buttons buttons_admin buttons_admin-pink">
    </div>
</form>
