<?php
/** @var $this \View\Template */
?>
<h1 class="header">Edit Databse</h1>

<div class="edit-window edit-window-container">

    <div class="edit-window__action">
        <label for="table-options">Which database do you want to edit?</label>
        <select name="filter" id="table-options">
            <option value="">Select...</option>
            <option data-database="Users" data-table="Users" value="Users">Users</option>
            <option data-database="Calculations" data-table="Calculations" value="Calculations">Calculations</option>
        </select>
    </div>
</div>
