<h1 class="header">Edit Databse</h1>

<div class="edit-window edit-window-container">

    <form data-form="get-data" action="/Calculation/Index/" method="POST" class="edit-window edit-window__form" id="edit-form-reset">
        <div class="edit-window__action">
            <label for="filter-options">What do you want to do</label>
            <select name="filter" id="filter-options">
                <option data-show-val="" value="">Select...</option>
                <option data-show-val="add" data-method="add" value="add">Add Data</option>
                <option data-show-val="update" data-method="update" value="update">Update Data</option>
                <option data-show-val="delete" data-method="delete" value="delete">Delete Data</option>
                <option data-show-val="filter" data-method="filter" value="filter">Filter Data</option>
                <option data-show-val="all" data-method="getAllData" value="getAllData">View All Data</option>
            </select>
        </div>

        <div class="edit-window__filters">

            <div class="edit-window__filters_options">
                <label for="columnName">Column Name
                    <select name="columnName" data-visible-for="update,delete,filter">
                        <option value="ip">IP</option>
                        <option value="date">Date</option>
                        <option value="calculation">Calculation</option>
                    </select>
                </label>
            </div>

            <div class="edit-window__filters_options">
                <div class="view_delete">
                    <label for="calculation">Data Point
                        <input type="text" name="calculation" data-visible-for="add,delete,filter">
                    </label>
                </div>

            </div>

            <div class="edit-window__filters_options">
                <label for="currentValue">Current Value
                    <input type="text" name="currentValue" data-visible-for="update">
                </label>

                <label for="newValue">New Value
                    <input type="text" name="newValue" data-visible-for="update">
                </label>
            </div>
        </div>
        <input type="submit" value="Submit" class="buttons buttons__admin">
        <div class="insert-message"></div>
    </form>

    <div class="database-display edit-window edit-window__form">
        <table>
            <?php



            ?>
            <tr class="table-headers">
                <!-- todo change this so it is pulled from the column names -->
                <th>ID</th>
                <th>IP Address</th>
                <th>Date</th>
                <th>Calculation</th>
            </tr>
        </table>

    </div>
</div>
