<h1 class="header">Kaafy's Way Better Calculator</h1>

<div class="container">

    <div class="container container_calculator">

        <div class="container container_display" id="display"></div>

        <div class="container container_buttons">

            <button class="buttons buttons_numeric" id="zero">0</button>
            <button class="buttons buttons_numeric" id="one">1</button>
            <button class="buttons buttons_numeric" id="two">2</button>
            <button class="buttons buttons_numeric" id="three">3</button>
            <button class="buttons buttons_numeric" id="four">4</button>
            <button class="buttons buttons_numeric" id="five">5</button>
            <button class="buttons buttons_numeric" id="six">6</button>
            <button class="buttons buttons_numeric" id="seven">7</button>
            <button class="buttons buttons_numeric" id="eight">8</button>
            <button class="buttons buttons_numeric" id="nine">9</button>

            <button class="buttons buttons_numeric_operator" id="addition">+</button>
            <button class="buttons buttons_numeric_operator" id="subtract">-</button>
            <button class="buttons buttons_numeric_operator" id="multiply">*</button>
            <button class="buttons buttons_numeric_operator" id="divide">/</button>

            <button class="buttons buttons_admin buttons_admin-blue" id="calculate">Calculate</button>
            <button class="buttons buttons_admin buttons_admin-orange" id="clear">Clear</button>

        </div>

    </div>

</div>
