<h1 class="header">Kaafy's Way Better Calculator</h1>

<div class="calculator">

    <div class="calculator calculator__container">

        <div class="calculator calculator__display" id="display"></div>

        <div class="buttons">

            <button class="buttons buttons__numeric" id="zero">0</button>
            <button class="buttons buttons__numeric" id="one">1</button>
            <button class="buttons buttons__numeric" id="two">2</button>
            <button class="buttons buttons__numeric" id="three">3</button>
            <button class="buttons buttons__numeric" id="four">4</button>
            <button class="buttons buttons__numeric" id="five">5</button>
            <button class="buttons buttons__numeric" id="six">6</button>
            <button class="buttons buttons__numeric" id="seven">7</button>
            <button class="buttons buttons__numeric" id="eight">8</button>
            <button class="buttons buttons__numeric" id="nine">9</button>

            <button class="buttons buttons__numeric buttons__numeric__operator" id="addition">+</button>
            <button class="buttons buttons__numeric buttons__numeric__operator" id="subtract">-</button>
            <button class="buttons buttons__numeric buttons__numeric__operator" id="multiply">*</button>
            <button class="buttons buttons__numeric buttons__numeric__operator" id="divide">/</button>

            <button class="buttons buttons__calculate" id="calculate">Calculate</button>
            <button class="buttons buttons__calculate buttons__calculate__clear" id="clear">Clear</button>

        </div>

    </div>

</div>
