<?php
/** @var $this \View\Template */
?>
<h1 class="header">Login</h1>
<div class="admin admin-container admin-login">
    <div class="admin-login__input">
        <label for="username">Username
            <input type="text" name="username">
        </label>
    </div>
    <div class="admin-login__input">
        <label for="password">Password
            <input type="text" name="password">
        </label>
    </div>
    <input type="submit" value="Submit" class="buttons buttons__admin">
    <div class="insert-message"></div>
</div>