<?php
/** @var $this \View\Template */
?>
<h1 class="header">Login</h1>
<div class="admin admin__container admin__login">
    <div class="admin__login-input">
        <label for="username">Username
            <input type="text" name="username">
        </label>
    </div>
    <div class="admin__login-input">
        <label for="password">Password
            <input type="text" name="password">
        </label>
    </div>
    <input type="submit" value="Submit" class="buttons buttons__admin buttons__login">
    <div class="insert-message"></div>
</div>