<?php
/** @var $this \View\Template */
?>
<div class="table-display container container_admin" id="table-element">
    <table class="container_table">
        <tr class="table-headers">
            <?php foreach ($this->columnNames as $name): ?>
                <th><?= $name ?></th>
            <?php endforeach; ?>
        </tr>
        <tr>
            <td>
            </td>
        </tr>
    </table>
</div>