<?php
/** @var $this \View\Template */
?>
<div class="table-display edit-window edit-window__form" id="table-element">
    <p>Table Display</p>
    <table>
        <tr class="table-headers">
<!--            --><?php //foreach($this->columnNames as $name): ?>
<!--            <th value="--><?php //echo $name ?><!--">--><?//= $name ?><!--</th>-->
<!--            --><?php //endforeach; ?>
        </tr>
        <tr>
            <td>
            </td>
        </tr>
    </table>
</div>