<?php
/** @var $this \View\Template */
?>

<form data-form="table-actions" method="POST" class="container container_admin" id="set-form-action">
    <div class="container_admin-input--medium container_admin-input--bold">
        <label for="filter-options">What do you want to do?</label>
        <select name="filter" id="filter-options">
            <option data-show-val="" value="">Select...</option>
            <option data-show-val="add" data-method="add" value="add">Add Data</option>
            <option data-show-val="update" data-method="update" value="update">Update Data</option>
            <option data-show-val="delete" data-method="delete" value="delete">Delete Data</option>
            <option data-show-val="filter" data-method="filter" value="filter">Filter Data</option>
            <option data-show-val="all" data-method="getAllData" value="getAllData">View All Data</option>
        </select>
    </div>

    <div class="container_admin-input--small" data-visible-for="hide,update,delete,filter">
        <label for="columnName">Column Name
            <select name="columnName">
                <option value="">Select...</option>
                <?php foreach($this->columnNames as $name): ?>
                    <option value="<?php echo $name ?>"><?= $name ?></option>
                <?php endforeach; ?>
            </select>
        </label>
    </div>

    <div class="container_admin-input--small" data-visible-for="hide,add">
        <div class="view_delete">
            <label for="inputValue">Input Value
                <input type="text" name="inputValue">
            </label>
        </div>
    </div>

    <div class="container_admin-input--small" data-visible-for="hide,delete,filter,update">
        <div class="view_delete">
            <label for="filterValue">Data Point
                <input type="text" name="filterValue">
            </label>
        </div>
    </div>

    <div class="container_admin-input--small" data-visible-for="hide,update">
        <label for="newValue">New Value
            <input type="text" name="newValue">
        </label>
    </div>
    <div class="container_buttons">
        <input type="submit" value="Submit" class="buttons buttons_admin buttons_admin-pink">
    </div>
    <div class="insert-message"></div>
</form>